# Generated by Django 5.1.4 on 2024-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orders_date_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
