# Generated by Django 5.1.4 on 2024-12-14 17:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='review',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
